source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '11.0'

target 'LYMobSDK_Example' do
  pod 'LYMobSDK', :path => '../'
  
#  pod 'LYMobSDK', '1.0.8'
  
  
  pod 'Masonry'

  target 'LYMobSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
