use_frameworks!

platform :ios, '10.0'

target 'LYMobSDK_Example' do
  pod 'LYMobSDK', :path => '../'
  
  
  pod 'Masonry'

  target 'LYMobSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
